[project]
name = "etl-loan-banking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "notebook>=7.4.3",
    "pandas>=2.3.0",
    "psycopg[binary]>=3.2.9",
    "requests>=2.32.4",
    "sqlalchemy>=2.0.41",
]
